#!/usr/bin/env python3
#
# Copyright 2023 BobRos
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import rclpy, sys
from rclpy.node import Node
from std_msgs.msg import String

class RosNode(Node):
    """Basic ROS Node"""
    def __init__(self):
        super().__init__('terminal_cli')

        self.sub = self.create_subscription(String, 'input_cli', 
            self.input_callback, 1000)            
        self.pub = self.create_publisher(String, 'input', 1000)

    def go(self):
        file_name = "/home/ros/ros2_ws/src/rosgpt4all/scripts/x"
        with open(file_name) as file:
            for line in file:
                self.publish(line)
                #self.pub.publish(String(data=line))
            #sys.exit(0)

    def input_callback(self, msg: String):
        """Process incoming topic message."""
        self.publish(msg.data)

    def publish(self, line: str):
        """Publish generated output."""
        self.get_logger().info(line)
        #rate = self.create_rate(1)
        for w in line.split():
            self.get_logger().info(w)
            msg = String()
            msg.data = w+" "
            self.pub.publish(msg)
            #rate.sleep()
        self.pub.publish(String(data="\n"))

def main():
    rclpy.init(args=None)
    n = RosNode()
    rclpy.spin(n)
    rclpy.shutdown()

if __name__ == '__main__':
    main()
